_wandb:
    value:
        cli_version: 0.25.0
        e:
            gzro0c9vwydrewxc1st8dmb0ftx3da9u:
                codePath: c:\Users\linmy\Age_Gender_predictor_CNN\src.ipynb
                codePathLocal: src.ipynb
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.5"
                disk:
                    /:
                        total: "511172407296"
                        used: "177174138880"
                email: linmyat9@gmail.com
                executable: c:\Users\linmy\Age_Gender_predictor_CNN\venv\Scripts\python.exe
                git:
                    commit: 5a4c97753b7217be5c837bb73533f6b0ca1b0b0d
                    remote: https://github.com/killuasmurf/Age_Gender_predictor_CNN.git
                gpu: NVIDIA GeForce RTX 3050 6GB Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2560
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3050 6GB Laptop GPU
                      uuid: GPU-08e2f7f6-0ae3-21f8-9b29-ea7b57f5390e
                host: linmyat
                memory:
                    total: "14702026752"
                os: Windows-11-10.0.22631-SP0
                program: c:\Users\linmy\Age_Gender_predictor_CNN\src.ipynb
                python: CPython 3.13.3
                root: c:\Users\linmy\Age_Gender_predictor_CNN
                startedAt: "2026-02-22T06:33:56.278705Z"
                writerId: gzro0c9vwydrewxc1st8dmb0ftx3da9u
        m: []
        python_version: 3.13.3
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 41
                - 49
                - 53
            "2":
                - 1
                - 2
                - 3
                - 5
                - 41
                - 49
                - 53
            "3":
                - 2
            "4": 3.13.3
            "5": 0.25.0
            "8":
                - 2
                - 1
                - 3
            "12": 0.25.0
            "13": windows-amd64
